name: dockle

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  dockle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run docker containers
        run: docker compose up -d
      - name: Run Dockle
        run: |
          VERSION=$(
            curl --silent "https://api.github.com/repos/goodwithtech/dockle/releases/latest" | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/' \
          )

          for image_name in $(docker compose images | awk 'OFS=":" {print $2,$3}' | tail -n +2); do
            cmd="docker run --rm -v /var/run/docker.sock:/var/run/docker.sock goodwithtech/dockle:v${VERSION} --exit-code 1 "

            if [[ "${image_name}" =~ "dss-notebook" ]]; then
              cmd+="--timeout 600s -ae mdf -af settings.py -af credentials -i DKL-DI-0001 "
            fi

            cmd+="${image_name}"
            echo "> ${cmd}"
            eval "${cmd}"
          done
